name: algebra
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0  
  firebase_auth: ^4.3.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.13.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  unicons: any
  google_fonts: ^5.1.0
  lottie: ^2.5.0
  intl: ^0.17.0
  connectivity: ^3.0.6
  shared_preferences: ^2.2.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  fluttertoast: ^8.2.2
  connectivity_plus: ^5.0.2

  

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  flutter_native_splash: ^2.2.4

  mocktail: ^1.0.1
  test: ^1.24.3
  fake_cloud_firestore: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf     
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf           
        
flutter_native_splash:
    image: assets/images/favicon.png  # Use your desired image path
    android: true
    ios: true
    web: false
 


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, ssee
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages