name: algebra
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0  
  firebase_auth: ^4.3.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.13.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  unicons: any
  google_fonts: ^5.1.0
  lottie: ^2.5.0
  intl: ^0.17.0
  connectivity: ^3.0.6
  shared_preferences: ^2.2.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  fluttertoast: ^8.2.2
  

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  flutter_native_splash: ^2.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_native_splash:
    color: "42a5f5"  # Use your desired background color
    image: assets/images/favicon.png  # Use your desired image path
    android: true
    ios: true
    web: false
 


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
