import 'package:injectable/injectable.dart';
import '../../../core/result/result.dart';
import '../../models/fritids_pass_registration_model.dart';
import '../../models/fritids_group.dart';
import '../../models/pass_type.dart';
import '../../repositories/i_fritids_repository.dart';
import '../../repositories/i_student_repository.dart';
import '../../repositories/i_auth_repository.dart';
import '../base_usecase.dart';

/// Parameters for registering a fritids pass
class RegisterFritidsPassParams extends Params {
  final String studentId;
  final String studentName;
  final FritidsGroup group;
  final PassType passType;

  const RegisterFritidsPassParams({
    required this.studentId,
    required this.studentName,
    required this.group,
    required this.passType,
  });

  @override
  Map<String, dynamic> toMap() => {
        'studentId': studentId,
        'studentName': studentName,
        'group': group.toValue(),
        'passType': passType.toValue(),
      };
}

/// Use case for registering a fritids pass
@lazySingleton
class RegisterFritidsPassUseCase
    extends BaseUseCase<String, RegisterFritidsPassParams> {
  final IFritidsRepository _fritidsRepository;
  final IStudentRepository _studentRepository;
  final IAuthRepository _authRepository;

  RegisterFritidsPassUseCase(
    this._fritidsRepository,
    this._studentRepository,
    this._authRepository,
  );

  @override
  Future<Result<String>> call(RegisterFritidsPassParams params) async {
    try {
      // Get current staff member
      final currentUser = _authRepository.currentUser;
      if (currentUser == null) {
        return const Failure(
          ValidationError(
            message: 'Du måste vara inloggad',
            code: 'NOT_AUTHENTICATED',
          ),
        );
      }

      // Get student info
      final student = await _studentRepository.getStudentById(params.studentId);
      if (student == null) {
        return const Failure(
          NotFoundError(
            message: 'Studenten hittades inte',
            code: 'STUDENT_NOT_FOUND',
          ),
        );
      }

      // Check if student belongs to this fritids group
      if (student.fritidsGroup != params.group) {
        return Failure(
          ValidationError(
            message: 'Studenten tillhör inte gruppen ${params.group.displayName}',
            code: 'INVALID_GROUP',
          ),
        );
      }

      final now = DateTime.now();
      final today = DateTime(now.year, now.month, now.day);

      // Check if already registered today for this pass
      final alreadyRegistered = await _fritidsRepository.hasRegisteredToday(
        params.studentId,
        params.group,
        params.passType,
        today,
      );

      if (alreadyRegistered) {
        return Failure(
          ValidationError(
            message:
                'Studenten har redan registrerats för ${params.passType.displayName} idag',
            code: 'ALREADY_REGISTERED',
          ),
        );
      }

      // Create registration
      final registration = FritidsPassRegistrationModel(
        id: '', // Will be generated by Firestore
        studentId: params.studentId,
        studentName: student.displayName,
        group: params.group,
        passType: params.passType,
        date: today,
        timestamp: now,
        staffId: currentUser.uid,
        staffName: currentUser.displayName ?? 'Staff',
        algebronaAwarded: 1,
      );

      // Register the pass
      final registrationId = await _fritidsRepository.registerPass(registration);

      // Update student coins
      await _studentRepository.updateStudentCoins(
        uid: params.studentId,
        coinChange: 1, // Award 1 Algebrona per pass
      );

      return Success(registrationId);
    } catch (e, stackTrace) {
      return Failure(
        UnknownError(
          message: 'Ett fel uppstod vid registrering av passet',
          originalError: e,
          stackTrace: stackTrace,
        ),
      );
    }
  }
}
