import 'coin_transaction_model.dart';

/// Model for batch transactions that can be reverted
class BatchTransactionModel {
  final String id;
  final String teacherId;
  final String teacherName;
  final DateTime timestamp;
  final List<StudentTransaction> studentTransactions;
  final int totalAmount;
  final bool isReverted;
  final String? revertedBy;
  final DateTime? revertedAt;

  BatchTransactionModel({
    required this.id,
    required this.teacherId,
    required this.teacherName,
    required this.timestamp,
    required this.studentTransactions,
    required this.totalAmount,
    this.isReverted = false,
    this.revertedBy,
    this.revertedAt,
  });

  factory BatchTransactionModel.fromMap(Map<String, dynamic> map, {String? id}) {
    return BatchTransactionModel(
      id: id ?? map['id'] ?? '',
      teacherId: map['teacherId'] ?? '',
      teacherName: map['teacherName'] ?? '',
      timestamp: map['timestamp'] is DateTime
          ? map['timestamp']
          : DateTime.fromMillisecondsSinceEpoch(map['timestamp'] ?? 0),
      studentTransactions: (map['studentTransactions'] as List<dynamic>?)
          ?.map((e) => StudentTransaction.fromMap(e))
          .toList() ?? [],
      totalAmount: map['totalAmount'] ?? 0,
      isReverted: map['isReverted'] ?? false,
      revertedBy: map['revertedBy'],
      revertedAt: map['revertedAt'] != null
          ? (map['revertedAt'] is DateTime
              ? map['revertedAt']
              : DateTime.fromMillisecondsSinceEpoch(map['revertedAt']))
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      // Don't include 'id' as it's generated by Firestore
      'teacherId': teacherId,
      'teacherName': teacherName,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'studentTransactions': studentTransactions.map((e) => e.toMap()).toList(),
      'totalAmount': totalAmount,
      'isReverted': isReverted,
      if (revertedBy != null) 'revertedBy': revertedBy,
      if (revertedAt != null) 'revertedAt': revertedAt!.millisecondsSinceEpoch,
    };
  }

  BatchTransactionModel copyWith({
    bool? isReverted,
    String? revertedBy,
    DateTime? revertedAt,
  }) {
    return BatchTransactionModel(
      id: id,
      teacherId: teacherId,
      teacherName: teacherName,
      timestamp: timestamp,
      studentTransactions: studentTransactions,
      totalAmount: totalAmount,
      isReverted: isReverted ?? this.isReverted,
      revertedBy: revertedBy ?? this.revertedBy,
      revertedAt: revertedAt ?? this.revertedAt,
    );
  }
}

/// Individual student transaction within a batch
class StudentTransaction {
  final String studentId;
  final String studentName;
  final int amount;
  final int previousCoins;
  final int newCoins;

  StudentTransaction({
    required this.studentId,
    required this.studentName,
    required this.amount,
    required this.previousCoins,
    required this.newCoins,
  });

  factory StudentTransaction.fromMap(Map<String, dynamic> map) {
    return StudentTransaction(
      studentId: map['studentId'] ?? '',
      studentName: map['studentName'] ?? '',
      amount: map['amount'] ?? 0,
      previousCoins: map['previousCoins'] ?? 0,
      newCoins: map['newCoins'] ?? 0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'studentId': studentId,
      'studentName': studentName,
      'amount': amount,
      'previousCoins': previousCoins,
      'newCoins': newCoins,
    };
  }
}